from .commande_repository import CommandeRepository
from .client_repository import ClientRepository
from .colis_repository import ColisRepository
from .departement_repository import DepartementRepository
from .commune_repository import CommuneRepository
from .detail_colis_repository import DetailColisRepository
from .detail_commande_repository import DetailCommandeRepository
from .objet_repository import ObjetRepository